// =========================================
// MULTIPLICATEUR DE DOMMAGE GLOBAL
// =========================================
export const MultiplicateurDeDommage = 1.2;

// =========================================
// LISTE DES SORTS
// =========================================
export const SPELLS = {
    // --- 1. DOMMAGE SIMPLE (68) ---

    // Sort basique Corps à Corps (CAC) - CD 0 – Type normal - portée non modifiable
    charge: { name: "Charge", range: 2, fixedRange: true, damage: 21, damageMin: 18, damageMax: 24, type: "normal", cooldown: 0, desc: "Comme un sanglier enragé, vous foncez tête baissée vers l'ennemi ! Avance d'une case et frappe. Parfait pour les débutants pressés !", icon: "🐗", animationWidth: 128, animationHeight: 96, animationDuration: 500, animationOnTarget: false, animationOnCaster: true, animationYOffset: 5, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    strike: { name: "Strike", range: 1, fixedRange: true, damage: 25, damageMin: 20, damageMax: 30, type: "normal", cooldown: 0, desc: "Le classique des classiques ! Un bon vieux coup de poing bien placé au corps à corps. Le sort qu'on utilise quand on ne sait pas quoi faire !", icon: "🗡️", animationWidth: 64, animationHeight: 64, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 5, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    kick: { name: "Kick", range: 2, fixedRange: true, damage: 23, damageMin: 20, damageMax: 26, type: "normal", cooldown: 0, desc: "Un coup de pied bien senti qui fait mal ! Parfait pour garder ses distances tout en frappant. Vous pouvez enchaîner comme un vrai karatéka !", icon: "👢", animationWidth: 80, animationHeight: 80, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 5, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    lifesteal: { name: "Lifesteal", range: 1, fixedRange: true, damage: 22, damageMin: 18, damageMax: 26, type: "normal", drain: 0.25, cooldown: 0, desc: "Frappez et récupérez ! Ce sort vampirique vous rend une partie de la vie volée. Parfait pour les combats longs - vous frappez, vous soignez, vous recommencez !", icon: "🧛", animationWidth: 64, animationHeight: 64, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 5, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    lasso: { name: "Lasso", range: 2, fixedRange: true, damage: 21, damageMin: 19, damageMax: 23, type: "normal", move_distance: 1, move_direction: "toward", cooldown: 0, desc: "Yeehaw ! Attrapez votre cible avec un lasso et tirez-la d'une case vers vous avant de la frapper. Le sort préféré des cowboys du combat !", icon: "🪢", animationWidth: 32, animationHeight: 32, animationDuration: 500, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 3, particleLifetime: 9000, particleColor: "#1A1A1A", particleRate: 500, trajectory: "small_sine" },
    trample: { name: "Trample", range: 1, fixedRange: true, damage: 20, damageMin: 18, damageMax: 22, type: "normal", effect_type: "debuff", stat: "pm", value: -1, duration: 1, cooldown: 0, desc: "Écrasez votre ennemi comme un éléphant ! Réduit les PM de la cible pendant 1 tour. Parfait pour ralentir les ennemis rapides - ils ne pourront plus bouger !", icon: "🐘", animationWidth: 64, animationHeight: 128, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 5, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    rage: { name: "Rage", range: 0, fixedRange: true, damage: 20, damageMin: 17, damageMax: 23, type: "normal", area: true, aoe_type: "cross", aoe_size: 1, effect_type: "buff", stat: "force", value: 30, duration: 2, cooldown: 0, desc: "La colère, c'est de l'énergie ! Explose de rage et frappe les 4 cases adjacentes, tout en augmentant votre force - c'est mathématique !", icon: "😠", animationWidth: 128, animationHeight: 128, animationDuration: 500, animationOnTarget: false, animationOnCaster: true, animationYOffset: 5, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    tiny_tail: { name: "Tiny Tail", range: 1, fixedRange: true, damage: 20, damageMin: 18, damageMax: 22, type: "normal", move_distance: 2, move_direction: "away", cooldown: 0, desc: "Un coup de queue tout mignon mais qui envoie loin ! C'est comme un coup de queue de chat, mais plus puissant !", icon: "🐉", animationWidth: 128, animationHeight: 80, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // Sort basique avec portée modifiable - CD 0
    peck: { name: "Peck", range: 3, fixedRange: false, damage: 17, damageMin: 15, damageMax: 19, type: "normal", cooldown: 0, desc: "Pic-pic-pic ! Comme un oiseau agressif, vous picorez l'ennemi de loin. Parfait pour harceler l'ennemi à distance - ils détestent ça !", icon: "🦅", animationWidth: 80, animationHeight: 80, animationDuration: 500, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    bite: { name: "Bite", range: 1, fixedRange: false, damage: 20, damageMin: 18, damageMax: 22, type: "dark", cooldown: 0, desc: "Une morsure ténébreuse qui fait mal ! Attention, ça peut faire saigner - et pas que physiquement !", icon: "🦷", animationWidth: 80, animationHeight: 80, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 15, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    needle: { name: "Needle", range: 2, fixedRange: false, damage: 19, damageMin: 17, damageMax: 21, type: "steel", cooldown: 0, desc: "Une aiguille d'acier bien pointue ! Petite mais douloureuse - comme une piqûre chez le médecin, mais en pire !", icon: "📌", animationWidth: 64, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    ember: { name: "Ember", range: 3, fixedRange: false, damage: 19, damageMin: 17, damageMax: 21, type: "fire", cooldown: 0, desc: "Une petite braise qui brûle ! Pas besoin d'allumettes, vous créez le feu vous-même !", icon: "🔥", animationWidth: 64, animationHeight: 64, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 10, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    bubble: { name: "Bubble", range: 3, fixedRange: false, damage: 19, damageMin: 17, damageMax: 21, type: "water", cooldown: 0, desc: "Des bulles d'eau qui font mal ? Oui, c'est possible ! Même les bulles peuvent être dangereuses dans ce jeu !", icon: "💧", animationWidth: 64, animationHeight: 64, animationDuration: 600, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    zap: { name: "Zap", range: 3, fixedRange: false, damage: 17, damageMin: 15, damageMax: 20, type: "electric", cooldown: 0, desc: "Zap ! Une petite décharge électrique qui surprend ! Parfait pour électrocuter vos ennemis à distance - ils vont adorer !", icon: "⚡", animationWidth: 64, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    leaf_blade: { name: "Leaf Blade", range: 3, fixedRange: false, damage: 19, damageMin: 17, damageMax: 21, type: "grass", cooldown: 0, desc: "Des feuilles tranchantes comme des lames ! Même les feuilles peuvent être des armes - la nature est cruelle !", icon: "🍃", animationWidth: 64, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    rock: { name: "Rock", range: 2, fixedRange: false, damage: 21, damageMin: 18, damageMax: 24, type: "ground", cooldown: 0, desc: "De bon vieux caillou bien lancé ! Simple, efficace, et ça fait toujours son effet - même David contre Goliath l'a utilisé !", icon: "🪨", animationWidth: 64, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    headache: { name: "Headache", range: 3, fixedRange: false, damage: 17, damageMin: 15, damageMax: 19, type: "psychic", cooldown: 0, desc: "Donnez un mal de tête à votre ennemi ! Psychologiquement douloureux - ils vont avoir mal à la tête pour de vrai !", icon: "💆", animationWidth: 96, animationHeight: 96, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    gust: { name: "Gust", range: 4, fixedRange: false, damage: 15, damageMin: 12, damageMax: 19, type: "wind", cooldown: 0, desc: "Un coup de vent qui décoiffe ! Parfait pour embêter l'ennemi de loin !", icon: "💨", animationWidth: 64, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    bash: { name: "Bash", range: 2, fixedRange: false, damage: 21, damageMin: 17, damageMax: 24, type: "steel", cooldown: 0, desc: "Un bon coup de bouclier en acier ! Le bouclier peut aussi servir d'arme !", icon: "🛡️", animationWidth: 64, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    scratch: { name: "Scratch", range: 2, fixedRange: false, damage: 23, damageMin: 20, damageMax: 26, type: "dragon", cooldown: 0, desc: "Un coup de griffe draconique qui déchire ! Les griffes de dragon, c'est tranchant - attention aux cicatrices !", icon: "💅", animationWidth: 64, animationHeight: 64, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    shadow_ball: { name: "Shadow Ball", range: 3, fixedRange: false, damage: 20, damageMin: 18, damageMax: 22, type: "dark", cooldown: 0, desc: "Une boule d'ombre qui fait peur ! Sombre, mystérieux, et ça fait mal - tout ce qu'on aime !", icon: "🎱", animationWidth: 64, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    light_ball: { name: "Light Ball", range: 4, fixedRange: false, damage: 16, damageMin: 13, damageMax: 19, type: "light", cooldown: 0, desc: "Une boule de lumière éclatante ! Comme un rayon de soleil, mais en version agressive !", icon: "✨", animationWidth: 56, animationHeight: 56, animationDuration: 500, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 3, particleLifetime: 1500, particleColor: "#FFD700", particleRate: 100, trajectory: "straight", continuousProjectile: false },

    // Sort Puissant CAC (Punchs) - CD 3 – 42 DMG - Portée 1 non modifiable
    magma_punch: { name: "Magma Punch", range: 1, fixedRange: true, damage: 40, damageMin: 35, damageMax: 45, type: "fire", cooldown: 3, desc: "Un poing enflammé qui brûle ! Votre poing devient littéralement du magma - attention aux brûlures !", icon: "🥊", animationWidth: 80, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    ice_punch: { name: "Ice Punch", range: 1, fixedRange: true, damage: 40, damageMin: 35, damageMax: 45, type: "water", cooldown: 3, desc: "Un poing glacé qui congèle ! Votre poing devient un glaçon géant - parfait pour refroidir les ardeurs ennemies !", icon: "🥊", animationWidth: 80, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    flower_punch: { name: "Flower Punch", range: 1, fixedRange: true, damage: 40, damageMin: 35, damageMax: 45, type: "grass", cooldown: 3, desc: "Un poing fleuri... mais qui fait mal ! Même les fleurs peuvent être violentes - ne vous fiez pas aux apparences !", icon: "🥊", animationWidth: 80, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    sand_punch: { name: "Sand Punch", range: 1, fixedRange: true, damage: 40, damageMin: 35, damageMax: 45, type: "ground", cooldown: 3, desc: "Un poing de sable qui gratte ! Comme un coup de poing dans le sable... mais en beaucoup plus dur !", icon: "🥊", animationWidth: 80, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    electro_punch: { name: "Electro Punch", range: 1, fixedRange: true, damage: 40, damageMin: 35, damageMax: 45, type: "electric", cooldown: 3, desc: "Un poing électrique qui électrocute ! Votre poing devient un générateur - les ennemis vont être choqués !", icon: "🥊", animationWidth: 80, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    tornado_punch: { name: "Tornado Punch", range: 1, fixedRange: true, damage: 40, damageMin: 35, damageMax: 45, type: "wind", cooldown: 3, desc: "Un poing tornade qui tourbillonne ! Votre poing crée une mini-tornade - les ennemis vont être emportés... par la douleur !", icon: "🥊", animationWidth: 80, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    dragon_punch: { name: "Dragon Punch", range: 1, fixedRange: true, damage: 40, damageMin: 35, damageMax: 45, type: "dragon", cooldown: 3, desc: "Un poing draconique légendaire ! La puissance des dragons concentrée dans votre poing - c'est du lourd !", icon: "🥊", animationWidth: 80, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    sunny_punch: { name: "Sunny Punch", range: 1, fixedRange: true, damage: 40, damageMin: 35, damageMax: 45, type: "light", cooldown: 3, desc: "Un poing solaire éclatant ! Votre poing brille comme le soleil - les ennemis vont être éblouis... et blessés !", icon: "🥊", animationWidth: 80, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    black_punch: { name: "Black Punch", range: 1, fixedRange: true, damage: 40, damageMin: 35, damageMax: 45, type: "dark", cooldown: 3, desc: "Un poing des ténèbres qui absorbe la lumière ! Votre poing devient noir comme la nuit - sombre et puissant !", icon: "🥊", animationWidth: 80, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    steel_punch: { name: "Steel Punch", range: 1, fixedRange: true, damage: 40, damageMin: 35, damageMax: 45, type: "steel", cooldown: 3, desc: "Un poing d'acier indestructible ! Votre poing devient métallique - dur comme de l'acier, fort comme un tank !", icon: "🥊", animationWidth: 80, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    psycho_punch: { name: "Psycho Punch", range: 1, fixedRange: true, damage: 40, damageMin: 35, damageMax: 45, type: "psychic", cooldown: 3, desc: "Un poing psychique qui attaque l'esprit ! Vous frappez avec votre esprit - c'est mentalement douloureux !", icon: "🥊", animationWidth: 80, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // Sort Puissant avec Portée modifiable - CD 3
    fireball: { name: "Fireball", range: 3, fixedRange: false, damage: 37, damageMin: 34, damageMax: 40, type: "fire", cooldown: 3, desc: "Une boule de feu qui explose ! La classique boule de feu des mages - efficace, spectaculaire, et ça brûle !", icon: "☄️", animationWidth: 80, animationHeight: 48, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    splash: { name: "Splash", range: 4, fixedRange: false, damage: 28, damageMin: 24, damageMax: 32, type: "water", cooldown: 3, desc: "Une grosse éclaboussure qui mouille ! Une goutte d'eau épaisse qui fait mal - comme une bombe à eau, mais en version magique !", icon: "💦", animationWidth: 64, animationHeight: 80, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 20, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    splash_v2: { name: "Wave", range: 3, fixedRange: false, damage: 36, damageMin: 34, damageMax: 38, type: "water", cooldown: 3, desc: "La version améliorée de l'éclaboussure ! Une vague qui emporte tout sur son passage - attention aux inondations !", icon: "🌊", animationWidth: 80, animationHeight: 80, animationDuration: 500, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    vine_whip: { name: "Vine Whip", range: 3, fixedRange: false, damage: 32, damageMin: 30, damageMax: 34, type: "grass", cooldown: 2, desc: "Un coup de fouet végétal qui fait mal ! Les plantes peuvent être méchantes, surtout quand elles vous fouettent !", icon: "🌿", animationWidth: 40, animationHeight: 40, animationDuration: 600, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 4, particleLifetime: 12000, particleColor: "#006400", particleRate: 500, trajectory: "small_sine" },
    thunder: { name: "Thunder", range: 3, fixedRange: false, damage: 36, damageMin: 30, damageMax: 42, type: "electric", cooldown: 3, desc: "Un éclair qui tombe du ciel ! Zeus serait fier - vous contrôlez la foudre maintenant !", icon: "🌩️", animationWidth: 64, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    tornado: { name: "Tornado", range: 4, fixedRange: false, damage: 35, damageMin: 32, damageMax: 38, type: "wind", cooldown: 4, desc: "Une tornade dévastatrice ! Parfait pour tourbillonner les ennemis de loin !", icon: "🌪️", animationWidth: 96, animationHeight: 96, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 15, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    fear: { name: "Fear", range: 2, fixedRange: false, damage: 40, damageMin: 38, damageMax: 42, type: "dark", cooldown: 3, desc: "La peur qui fait mal ! Vous effrayez l'ennemi... et en plus ça fait mal ! La peur est une arme !", icon: "👻", animationWidth: 80, animationHeight: 48, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    smite: { name: "Smite", range: 3, fixedRange: false, damage: 35, damageMin: 30, damageMax: 40, type: "light", cooldown: 3, desc: "Le châtiment divin ! La justice divine frappe - les méchants vont payer !", icon: "🌟", animationWidth: 96, animationHeight: 128, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    iron_head: { name: "Iron Head", range: 2, fixedRange: false, damage: 42, damageMin: 38, damageMax: 46, type: "steel", cooldown: 3, desc: "Un coup de boule en acier ! Votre tête devient métallique - dur comme de l'acier, fort comme un marteau !", icon: "🔩", animationWidth: 64, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    mind: { name: "Mind", range: 3, fixedRange: false, damage: 34, damageMin: 30, damageMax: 38, type: "psychic", cooldown: 3, desc: "Une attaque mentale puissante ! Vous attaquez avec votre esprit - c'est mentalement destructeur !", icon: "🧠", animationWidth: 64, animationHeight: 64, animationDuration: 500, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    rock_slide: { name: "Rock Slide", range: 3, fixedRange: false, damage: 35, damageMin: 28, damageMax: 44, type: "ground", cooldown: 3, desc: "Un éboulement de rochers ! Les rochers tombent du ciel - attention en dessous !", icon: "🪨", animationWidth: 96, animationHeight: 96, animationDuration: 800, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "parabolic" },
    meteor: { name: "Meteor", range: 3, fixedRange: false, damage: 37, damageMin: 32, damageMax: 42, type: "dragon", cooldown: 4, desc: "Un météore draconique qui tombe ! Vous invoquez un météore du ciel - les dinosaures savaient de quoi ils parlaient !", icon: "☄️", animationWidth: 150, animationHeight: 180, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // Sort en Zone avec portée modifiable
    spinning_punch: { name: "Spinning Punch", range: 0, fixedRange: true, damage: 38, damageMin: 35, damageMax: 41, type: "normal", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 3, desc: "Tournez comme une toupie et frappez tout autour ! Parfait quand vous êtes entouré - vous frappez dans tous les sens !", icon: "🥊", animationWidth: 200, animationHeight: 200, animationDuration: 900, animationOnTarget: false, animationOnCaster: true, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    fire_cross: { name: "Fire Cross", range: 3, fixedRange: false, damage: 31, damageMin: 28, damageMax: 34, type: "fire", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 4, desc: "Une croix de feu qui brûle ! Le feu en forme de croix - même les symboles peuvent brûler !", icon: "✖️", animationWidth: 128, animationHeight: 128, animationDuration: 450, animationOnTarget: true, animationOnCaster: false, animationYOffset: 30, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    leaf_storm: { name: "Leaf Storm", range: 1, fixedRange: true, damage: 30, damageMin: 27, damageMax: 33, type: "grass", area: true, aoe_type: "cone", aoe_size: 3, cooldown: 3, desc: "Une tempête de feuilles et de fleurs ! Même les fleurs peuvent être violentes - attention aux allergies ET aux dégâts !", icon: "🍃", animationWidth: 160, animationHeight: 160, animationDuration: 500, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 2, particleLifetime: 3000, particleColor: "#2E8B57", particleRate: 25, trajectory: "straight" },
    tsunami: { name: "Tsunami", range: 1, fixedRange: true, damage: 33, damageMin: 30, damageMax: 36, type: "water", area: true, aoe_type: "cone", aoe_size: 4, cooldown: 5, desc: "Une vague massive qui engloutit tout ! Une vraie vague de tsunami - les ennemis vont être emportés par le courant !", icon: "🌊", animationWidth: 256, animationHeight: 320, animationDuration: 1000, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    overload: { name: "Overload", range: 0, fixedRange: true, damage: 36, damageMin: 33, damageMax: 39, type: "electric", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 4, desc: "Une surcharge électrique explosive ! Vous surchargez et électrocutez tout autour - attention aux courts-circuits !", icon: "💥", animationWidth: 160, animationHeight: 160, animationDuration: 400, animationOnTarget: false, animationOnCaster: true, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    wind_tunnel: { name: "Wind Tunnel", range: 1, fixedRange: true, damage: 31, damageMin: 29, damageMax: 33, type: "wind", area: true, aoe_type: "line", aoe_size: 5, cooldown: 3, desc: "Un tunnel de vent destructeur ! Un vent si fort qu'il fait mal - comme un ouragan en version compacte !", icon: "🌬️", animationWidth: 96, animationHeight: 96, animationDuration: 600, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 2, particleLifetime: 3000, particleColor: "#FFFFFF", particleRate: 20, trajectory: "straight" },
    iron_hail: { name: "Iron Hail", range: 3, fixedRange: false, damage: 31, damageMin: 28, damageMax: 34, type: "steel", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 3, desc: "Une pluie de plomb métallique ! Il pleut des morceaux d'acier - mieux vaut avoir un parapluie... en acier !", icon: "🔩", animationWidth: 128, animationHeight: 160, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    shadow: { name: "Shadow", range: 3, fixedRange: false, damage: 33, damageMin: 30, damageMax: 36, type: "dark", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 4, desc: "Une ombre des ténèbres qui engloutit ! L'ombre devient agressive - même les ombres peuvent faire mal !", icon: "🌑", animationWidth: 96, animationHeight: 96, animationDuration: 450, animationOnTarget: true, animationOnCaster: false, animationYOffset: 20, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    sandblast: { name: "Sandblast", range: 4, fixedRange: false, damage: 27, damageMin: 24, damageMax: 30, type: "ground", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 3, desc: "Un jet de sable abrasif ! Parfait pour sabler les ennemis de loin !", icon: "🏜️", animationWidth: 160, animationHeight: 160, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    dragon_breath: { name: "Dragon Breath", range: 1, fixedRange: true, damage: 34, damageMin: 30, damageMax: 38, type: "dragon", area: true, aoe_type: "cone", aoe_size: 3, cooldown: 5, desc: "Le souffle légendaire du dragon ! Le souffle des dragons - puissant, destructeur, et ça sent le soufre !", icon: "🐲", animationWidth: 128, animationHeight: 160, animationDuration: 500, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    radiance: { name: "Radiance", range: 0, fixedRange: true, damage: 35, damageMin: 30, damageMax: 40, type: "light", area: true, aoe_type: "circular", aoe_size: 2, cooldown: 4, desc: "Un rayonnement lumineux éclatant ! Vous brillez comme le soleil - et ça brûle aussi !", icon: "✨", animationWidth: 256, animationHeight: 256, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    madness_wave: { name: "Madness Wave", range: 2, fixedRange: false, damage: 32, damageMin: 29, damageMax: 35, type: "psychic", area: true, aoe_type: "cone", aoe_size: 2, cooldown: 3, desc: "Une vague de folie mentale ! Vous propagez la folie - les ennemis vont devenir fous... et prendre des dégâts !", icon: "🌀", animationWidth: 128, animationHeight: 128, animationDuration: 500, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    electric_chain: { name: "Electric Chain", range: 3, fixedRange: false, damage: 31, damageMin: 28, damageMax: 34, type: "electric", area: true, aoe_type: "chain", aoe_size: 2, cooldown: 4, desc: "Un courant électrique en chaîne ! L'électricité saute d'ennemi en ennemi - comme un éclair en chaîne !", icon: "🔗", animationWidth: 64, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // Sort Surpuissants - portée non modifiable
    hyper_beam: { name: "Hyper Beam", range: 2, fixedRange: true, damage: 65, damageMin: 60, damageMax: 70, type: "normal", cooldown: 8, desc: "Le rayon ultime de destruction ! Un sort surpuissant qui inflige des dégâts colossaux. Parfait pour les coups de grâce dévastateurs !", icon: "💥", animationWidth: 64, animationHeight: 64, animationDuration: 700, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 12, particleLifetime: 18000, particleColor: "#FFD700", particleRate: 500, trajectory: "straight", continuousProjectile: false },
    fire_blast: { name: "Fire Blast", range: 2, fixedRange: true, damage: 60, damageMin: 55, damageMax: 65, type: "fire", cooldown: 7, desc: "Une déflagration de feu explosive ! Une explosion de feu si puissante qu'elle fait trembler le sol - les ennemis vont être carbonisés !", icon: "🌋", animationWidth: 64, animationHeight: 64, animationDuration: 600, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 8, particleLifetime: 8000, particleColor: "#FF2400", particleRate: 500, trajectory: "straight" },
    solar_beam: { name: "Solar Beam", range: 2, fixedRange: true, damage: 60, damageMin: 55, damageMax: 65, type: "grass", cooldown: 7, desc: "Un rayon solaire concentré ! Vous concentrez la puissance du soleil - même les plantes peuvent être destructrices avec assez de lumière !", icon: "☀️", animationWidth: 48, animationHeight: 48, animationDuration: 600, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 8, particleLifetime: 8000, particleColor: "#DFFF00", particleRate: 500, trajectory: "straight" },
    hydro_pump: { name: "Hydro Pump", range: 2, fixedRange: true, damage: 60, damageMin: 55, damageMax: 65, type: "water", cooldown: 7, desc: "Un canon à eau surpuissant ! Comme un tuyau d'arrosage, mais en version destructrice - la pression est mortelle !", icon: "💧", animationWidth: 64, animationHeight: 64, animationDuration: 600, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 8, particleLifetime: 8000, particleColor: "#70D1F4", particleRate: 500, trajectory: "straight" },
    thunderbolt: { name: "Thunderbolt", range: 2, fixedRange: true, damage: 55, damageMin: 50, damageMax: 60, type: "electric", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 7, desc: "La foudre fatale qui frappe ! Un éclair si puissant qu'il électrocute toute la zone - Zeus serait jaloux !", icon: "⚡", animationWidth: 180, animationHeight: 180, animationDuration: 800, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    storm: { name: "Storm", range: 2, fixedRange: true, damage: 55, damageMin: 50, damageMax: 60, type: "wind", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 6, desc: "Une tempête intense et destructrice ! Un ouragan concentré - les ennemis vont être emportés par la tempête !", icon: "🌪️", animationWidth: 180, animationHeight: 160, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 15, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    quake: { name: "Quake", range: 2, fixedRange: true, damage: 55, damageMin: 50, damageMax: 60, type: "ground", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 7, desc: "Un séisme qui fissure le sol ! Vous créez un tremblement de terre - le sol se fissure sous les pieds de l'ennemi !", icon: "🌋", animationWidth: 96, animationHeight: 96, animationDuration: 450, animationOnTarget: true, animationOnCaster: false, animationYOffset: 40, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    schizophrenia: { name: "Schizophrenia", range: 2, fixedRange: true, damage: 60, damageMin: 64, damageMax: 66, type: "psychic", cooldown: 8, desc: "Fendez le crâne mentalement ! Vous attaquez l'esprit si violemment que vous fendez littéralement le crâne - mentalement, mais ça fait mal quand même !", icon: "🧠", animationWidth: 128, animationHeight: 128, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    dragon_rage: { name: "Dragon Rage", range: 0, fixedRange: true, damage: 65, damageMin: 62, damageMax: 68, type: "dragon", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 8, desc: "La colère du dragon explose ! Mieux vaut ne pas être dans les parages - la colère draconique est dévastatrice !", icon: "🐉", animationWidth: 192, animationHeight: 192, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    damocles_sword: { name: "Damocles Sword", range: 2, fixedRange: true, damage: 61, damageMin: 60, damageMax: 62, type: "steel", cooldown: 7, desc: "L'épée de Damoclès qui tombe ! Littéralement l'épée de Damoclès qui tombe sur la nuque de l'ennemi - la légende devient réalité !", icon: "⚔️", animationWidth: 92, animationHeight: 256, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: -50, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    supernova: { name: "Supernova", range: 2, fixedRange: true, damage: 55, damageMin: 50, damageMax: 60, type: "light", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 8, desc: "L'explosion d'une étoile ! Vous faites exploser une étoile - c'est spectaculaire et destructeur !", icon: "🌟", animationWidth: 256, animationHeight: 256, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    black_hole: { name: "Black Hole", range: 2, fixedRange: true, damage: 53, damageMin: 48, damageMax: 58, type: "dark", area: true, aoe_type: "circular", aoe_size: 1, drain: 0.25, cooldown: 8, desc: "Un trou noir qui absorbe la vie ! Le trou noir absorbe toute l'énergie vitale - et vous en récupérez une partie !", icon: "⚫", animationWidth: 192, animationHeight: 192, animationDuration: 550, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // Sorts Surpuissants au CAC - CD 8 - portée non modifiable
    giga_punch: { name: "Giga Punch", range: 1, fixedRange: true, damage: 68, damageMin: 63, damageMax: 73, type: "normal", cooldown: 8, desc: "Le poing géant ultime ! Votre poing devient gigantesque - un coup si puissant qu'il peut tout détruire !", icon: "👊", animationWidth: 128, animationHeight: 196, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    massive_absorption: { name: "Massive Absorption", range: 1, fixedRange: true, damage: 55, damageMin: 51, damageMax: 59, type: "normal", drain: 0.5, cooldown: 8, desc: "L'absorption vampirique ultime ! Vous absorbez la moitié de la vie de l'ennemi - vous devenez un vrai vampire !", icon: "🧛", animationWidth: 160, animationHeight: 160, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    self_destruction: { name: "Self-Destruction", range: 0, fixedRange: true, damage: 100, damageMin: 90, damageMax: 110, type: "normal", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 8, self_ko: true, desc: "L'ultime sacrifice ! Vous vous auto-détruisez pour infliger des dégâts colossaux - attention, vous serez KO après ! Le sort kamikaze ultime !", icon: "💣", animationWidth: 192, animationHeight: 192, animationDuration: 600, animationOnTarget: true, animationOnCaster: true, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // Sort avec effet de poison
    apple_die: { name: "Apple Die", range: 2, fixedRange: false, damage: 15, damageMin: 10, damageMax: 20, type: "dark", effect_type: "damage_over_time", value: 0.1, duration: 3, cooldown: 4, desc: "La pomme empoisonnée de Blanche-Neige ! Elle a l'air appétissante... mais elle est mortelle !", icon: "🍎", animationWidth: 80, animationHeight: 80, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    snake_juice: { name: "Snake Juice", range: 3, fixedRange: false, damage: 12, damageMin: 8, damageMax: 16, type: "normal", effect_type: "damage_over_time", value: 0.1, duration: 3, cooldown: 3, desc: "Du venin de serpent... discrètement fruité ! Le venin le plus délicieux (et mortel) que vous ayez jamais goûté !", icon: "☣️", animationWidth: 80, animationHeight: 80, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    toxic_spike: { name: "Toxic Spike", range: 2, fixedRange: false, damage: 18, damageMin: 14, damageMax: 22, type: "grass", effect_type: "damage_over_time", value: 0.1, duration: 3, cooldown: 5, desc: "Une épine venimeuse bien pointue ! Même les plantes peuvent être toxiques - attention aux épines !", icon: "🌿", animationWidth: 64, animationHeight: 32, animationDuration: 500, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    irritating_pollen: { name: "Irritating Pollen", range: 2, fixedRange: false, damage: 14, damageMin: 10, damageMax: 18, type: "grass", area: true, aoe_type: "circular", aoe_size: 2, effect_type: "damage_over_time", value: 0.1, duration: 3, cooldown: 5, desc: "Du pollen qui brûle les yeux et irrite le nez ! Parfait pour les allergiques... et les ennemis !", icon: "🌼", animationWidth: 256, animationHeight: 256, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    intoxicating_wind: { name: "Intoxicating Wind", range: 2, fixedRange: false, damage: 13, damageMin: 11, damageMax: 15, type: "wind", area: true, aoe_type: "circular", aoe_size: 1, effect_type: "damage_over_time", value: 0.1, duration: 3, cooldown: 4, desc: "Un vent d'une composition inconnue qui empoisonne ! Mieux vaut ne pas respirer ce vent - il est toxique !", icon: "💨", animationWidth: 192, animationHeight: 192, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // Sort dommage avec Statuts Altérés (25% de chance)
    ice_shard: { name: "Ice Shard", range: 3, fixedRange: false, damage: 26, damageMin: 23, damageMax: 29, type: "water", effect_type: "control", control_effect: "paralyzed", duration: 2, effect_chance: 0.25, cooldown: 5, desc: "Des éclats de glace qui paralysent ! La glace peut geler les membres - attention aux engelures !", icon: "🧊", animationWidth: 80, animationHeight: 80, animationDuration: 500, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    electro_shock: { name: "Electro-Shock", range: 3, fixedRange: false, damage: 25, damageMin: 23, damageMax: 27, type: "electric", area: true, aoe_type: "circular", aoe_size: 1, effect_type: "control", control_effect: "paralyzed", duration: 2, effect_chance: 0.25, cooldown: 5, desc: "Une bombe électrique paralysante ! L'électricité peut paralyser - comme une décharge électrique, mais en pire !", icon: "⚡", animationWidth: 128, animationHeight: 128, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    nightmare: { name: "Nightmare", range: 2, fixedRange: false, damage: 28, damageMin: 25, damageMax: 31, type: "psychic", effect_type: "control", control_effect: "sleep", duration: 2, effect_chance: 0.25, cooldown: 5, desc: "Dévorez les rêves de votre ennemi ! 25% de chance d'endormir la cible pendant 1 tours. Vous attaquez les rêves - et parfois l'ennemi s'endort de peur !", icon: "😵", animationWidth: 64, animationHeight: 192, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    philosophy: { name: "Philosophy", range: 4, fixedRange: false, damage: 23, damageMin: 21, damageMax: 25, type: "light", area: true, aoe_type: "circular", aoe_size: 1, effect_type: "control", control_effect: "sleep", duration: 2, effect_chance: 0.35, cooldown: 5, desc: "Un cours de philosophie... qui endort ! Même la philosophie peut être une arme - les ennemis s'endorment d'ennui !", icon: "📚", animationWidth: 128, animationHeight: 128, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    stunning_hammer: { name: "Stunning Hammer", range: 1, fixedRange: true, damage: 40, damageMin: 36, damageMax: 44, type: "steel", effect_type: "control", control_effect: "sleep", duration: 2, effect_chance: 0.25, cooldown: 5, desc: "Un gros coup de marteau sur la tête ! 25% de chance d'étourdir pendant 1 tour. Un coup sur l'occiput - ça peut étourdir... ou pire !", icon: "🔨", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 20, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    tremor: { name: "Tremor", range: 0, fixedRange: false, damage: 20, damageMin: 18, damageMax: 22, type: "ground", area: true, aoe_type: "circular", aoe_size: 2, effect_type: "control", control_effect: "fragile", duration: 3, effect_chance: 0.5, cooldown: 5, desc: "Un tremblement de terre qui déstabilise la marche ! Le séisme ultime - même le terrain tremble !", icon: "🌋", animationWidth: 256, animationHeight: 256, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    dragon_cry: { name: "Dragon Cry", range: 3, fixedRange: false, damage: 30, damageMin: 26, damageMax: 34, type: "dragon", effect_type: "control", control_effect: "fragile", duration: 2, effect_chance: 0.5, cooldown: 5, desc: "Le cri perçant du dragon ! 25% de chance de fragiliser pendant 2 tour.Le cri est si perçant qu'il peut fragiliser l'ennemi - attention aux tympans !", icon: "🐉", animationWidth: 128, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    ignite: { name: "Ignite", range: 3, fixedRange: false, damage: 34, damageMin: 30, damageMax: 38, type: "fire", effect_type: "control", control_effect: "burn", duration: 3, effect_chance: 0.5, cooldown: 5, desc: "Un feu incandescent qui brûle ! Le feu est si intense qu'il peut mettre le feu à l'ennemi - attention aux brûlures !", icon: "🌋", animationWidth: 80, animationHeight: 128, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    delicate_feather: { name: "Delicate Feather", range: 3, fixedRange: false, damage: 20, damageMin: 16, damageMax: 24, type: "normal", effect_type: "control", control_effect: "sleep", duration: 2, effect_chance: 0.5, cooldown: 5, desc: "Une plume délicate qui endort ! 50% de chance d'endormir la cible. Une plume si douce qu'elle berce l'ennemi dans un sommeil profond !", icon: "🪶", animationWidth: 64, animationHeight: 128, animationDuration: 800, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // Dommage + Déplacement
    assault: { name: "Assault", range: 5, fixedRange: false, damage: 24, damageMin: 22, damageMax: 26, type: "normal", area: true, aoe_type: "circular", aoe_size: 1, effect_type: "movement", move_direction: "teleport_adj", cooldown: 4, desc: "L'assaut téléporté ! Frappez en arrivant - l'effet de surprise est garanti !", icon: "⚔️", animationWidth: 128, animationHeight: 128, animationDuration: 500, animationOnTarget: false, animationOnCaster: true, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    elasto_punch: { name: "Elasto-punch", range: 4, fixedRange: false, damage: 26, damageMin: 23, damageMax: 29, type: "normal", move_distance: 3, move_direction: "toward", cooldown: 4, desc: "Le poing élastique qui attire ! Attirez la cible en ligne droite (croix) vers vous avant de la frapper. La cible glisse jusqu'à la case adjacente au lanceur. Comme un poing élastique - vous attirez et vous frappez !", icon: "🥊", animationWidth: 64, animationHeight: 64, animationDuration: 500, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 5, particleLifetime: 7000, particleColor: "#3E2723", particleRate: 500, trajectory: "small_sine" },
    home_run: { name: "Home Run", range: 1, fixedRange: true, damage: 30, damageMin: 28, damageMax: 32, type: "normal", move_distance: 6, move_direction: "away", cooldown: 4, desc: "Le home run ultime ! Frappez avec une batte au corps à corps. L'ennemi va voler comme une balle de baseball !", icon: "⚾", animationWidth: 128, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    repelling_bomb: { name: "Repelling Bomb", range: 5, fixedRange: false, damage: 12, damageMin: 10, damageMax: 14, type: "normal", area: true, aoe_type: "circular", aoe_size: 1, move_distance: 3, move_direction: "away", cooldown: 3, desc: "Une bombe qui repousse en zone ! Si la cible est sur la case ciblée, elle ne bouge pas. Si elle est adjacente, elle est repoussée de 3 cases dans la direction de la ligne case cible → case adjacente. Peut également déplacer le lanceur ou des cibles alliées sans leur faire de dégâts.", icon: "💣", animationWidth: 128, animationHeight: 128, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    dragon_tail: { name: "Dragon Tail", range: 1, fixedRange: true, damage: 28, damageMin: 26, damageMax: 30, type: "dragon", move_distance: 3, move_direction: "away", cooldown: 4, desc: "Un coup de queue draconique qui envoie loin ! La queue du dragon est puissante - l'ennemi va voler à perpète !", icon: "🐉", animationWidth: 80, animationHeight: 80, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // --- 3. BUFF / DEBUFF (43) ---

    // Auto-Buff - CD 4 – effet pendant 3 tours - portée 0 – type normal
    speed: { name: "Speed", range: 0, fixedRange: true, effect_type: "buff", stat: "pm", value: 2, duration: 3, type: "normal", cooldown: 4, desc: "La vitesse, c'est la vie ! Vous devenez plus rapide - comme Flash, mais en version magique !", icon: "⚡", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    solid_hand: { name: "Solid Hand", range: 0, fixedRange: true, effect_type: "buff", stat: "crit_chance", value: 0.2, duration: 3, type: "normal", cooldown: 4, desc: "Une main solide pour les coups critiques ! Votre main devient plus précise - les critiques vont pleuvoir !", icon: "👊", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    bodybuilding: { name: "Bodybuilding", range: 0, fixedRange: true, effect_type: "buff", stat: "force", value: 100, duration: 3, type: "normal", cooldown: 4, desc: "La musculation instantanée ! Pas besoin de salle de sport - vous devenez musclé instantanément !", icon: "💪", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    solid_heart: { name: "Solid Heart", range: 0, fixedRange: true, effect_type: "buff", stat: "maxHp", value: 100, duration: 3, type: "normal", cooldown: 4, desc: "Un cœur solide qui résiste ! Votre cœur devient plus résistant - vous pouvez encaisser plus de coups !", icon: "❤️", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    haste: { name: "Haste", range: 0, fixedRange: true, effect_type: "buff", stat: "evasion", value: 15, duration: 3, type: "normal", cooldown: 4, desc: "La hâte qui fait esquiver ! Vous devenez plus rapide - les attaques vous ratent comme par magie !", icon: "🏃", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    vision: { name: "Vision", range: 0, fixedRange: true, effect_type: "buff", stat: "range", value: 2, duration: 3, type: "normal", cooldown: 4, desc: "Une vision améliorée ! Vous voyez plus loin - comme des jumelles magiques intégrées !", icon: "👁️", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    shield: { name: "Shield", range: 0, fixedRange: true, effect_type: "control", control_effect: "dmg_taken_multiplier", value: 0.9, duration: 3, type: "normal", cooldown: 4, desc: "Un bouclier protecteur ! Un bouclier magique qui vous protège - les coups font moins mal !", icon: "🛡️", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // Buffs de groupe (Mass Buffs) - CD4 – effet pendant 2 tours - portée 3 – zone circulaire d'une case – type normal
    mass_acceleration: { name: "Mass Acceleration", range: 3, fixedRange: false, effect_type: "buff", stat: "pm", value: 1, duration: 2, type: "normal", area: true, aoe_type: "circular", aoe_size: 2, cooldown: 4, desc: "L'accélération de groupe ! Toute l'équipe devient plus rapide - comme une équipe de Formule 1 !", icon: "⚡", animationWidth: 256, animationHeight: 256, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -60, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    mass_focus: { name: "Mass Focus", range: 3, fixedRange: false, effect_type: "buff", stat: "crit_chance", value: 0.15, duration: 2, type: "normal", area: true, aoe_type: "circular", aoe_size: 2, cooldown: 4, desc: "Le focus de groupe ! Toute l'équipe devient plus précise - les critiques vont pleuvoir !", icon: "🎯", animationWidth: 256, animationHeight: 256, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -60, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    mass_power: { name: "Mass Power", range: 3, fixedRange: false, effect_type: "buff", stat: "force", value: 80, duration: 2, type: "normal", area: true, aoe_type: "circular", aoe_size: 2, cooldown: 4, desc: "La puissance de groupe ! Toute l'équipe devient plus forte - comme une salle de sport collective !", icon: "💪", animationWidth: 256, animationHeight: 256, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -60, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    mass_vitality: { name: "Mass Vitality", range: 3, fixedRange: false, effect_type: "buff", stat: "maxHp", value: 80, duration: 2, type: "normal", area: true, aoe_type: "circular", aoe_size: 2, cooldown: 4, desc: "La vitalité de groupe ! Toute l'équipe devient plus résistante - comme une armure collective !", icon: "❤️", animationWidth: 256, animationHeight: 256, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -60, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    mass_reflect: { name: "Mass Reflect", range: 3, fixedRange: false, effect_type: "buff", stat: "evasion", value: 10, duration: 2, type: "normal", area: true, aoe_type: "circular", aoe_size: 2, cooldown: 4, desc: "L'esquive de groupe ! Toute l'équipe devient plus agile - les attaques vous ratent en groupe !", icon: "🪞", animationWidth: 256, animationHeight: 256, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -60, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    mass_extension: { name: "Mass Extension", range: 3, fixedRange: false, effect_type: "buff", stat: "range", value: 1, duration: 2, type: "normal", area: true, aoe_type: "circular", aoe_size: 2, cooldown: 4, desc: "La portée de groupe ! Toute l'équipe voit plus loin - comme des jumelles partagées !", icon: "📏", animationWidth: 256, animationHeight: 256, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -60, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    mass_hardening: { name: "Mass Hardening", range: 3, fixedRange: false, effect_type: "control", control_effect: "dmg_taken_multiplier", value: 0.9, duration: 2, type: "normal", area: true, aoe_type: "circular", aoe_size: 2, cooldown: 4, desc: "Le durcissement de groupe ! Toute l'équipe devient plus résistante - comme une armure collective !", icon: "🛡️", animationWidth: 256, animationHeight: 256, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -60, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // Buffs ciblés (Targeted Buffs) - portée 3 – CD5 – effet pendant 3 tours – cible unique – type normal
    acceleration: { name: "Acceleration", range: 3, fixedRange: false, effect_type: "buff", stat: "pm", value: 2, duration: 3, type: "normal", cooldown: 5, desc: "L'accélération ciblée ! La cible devient super rapide - comme un éclair personnalisé !", icon: "⚡", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    focus: { name: "Focus", range: 3, fixedRange: false, effect_type: "buff", stat: "crit_chance", value: 0.3, duration: 3, type: "normal", cooldown: 5, desc: "Le focus ciblé ! La cible devient ultra-précise - les critiques vont fuser !", icon: "🎯", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    power: { name: "Power", range: 3, fixedRange: false, effect_type: "buff", stat: "force", value: 200, duration: 3, type: "normal", cooldown: 5, desc: "La puissance ciblée ! La cible devient surpuissante - comme Hulk, mais en version magique !", icon: "💪", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    vitality: { name: "Vitality", range: 3, fixedRange: false, effect_type: "buff", stat: "maxHp", value: 200, duration: 3, type: "normal", cooldown: 5, desc: "La vitalité ciblée ! La cible devient ultra-résistante - comme un tank personnalisé !", icon: "❤️", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    reflect: { name: "Reflect", range: 3, fixedRange: false, effect_type: "buff", stat: "evasion", value: 20, duration: 3, type: "normal", cooldown: 5, desc: "L'esquive ciblée ! La cible devient insaisissable - comme un ninja magique !", icon: "🪞", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    extension: { name: "Extension", range: 3, fixedRange: false, effect_type: "buff", stat: "range", value: 2, duration: 3, type: "normal", cooldown: 5, desc: "La portée ciblée ! La cible voit beaucoup plus loin - comme des télescopes magiques !", icon: "📏", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    hardening: { name: "Hardening", range: 3, fixedRange: false, effect_type: "control", control_effect: "dmg_taken_multiplier", value: 0.8, duration: 3, type: "normal", cooldown: 5, desc: "Le durcissement ciblé ! La cible devient ultra-résistante - comme une armure magique personnalisée !", icon: "🛡️", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    loto: {
        name: "LOTO", range: 3, fixedRange: false, effect_type: "random_buff", random_buffs: [
            { type: "buff", stat: "pm", value: 1, duration: 3 },
            { type: "buff", stat: "maxHp", value: 100, duration: 3 },
            { type: "buff", stat: "force", value: 100, duration: 3 },
            { type: "buff", stat: "range", value: 1, duration: 3 },
            { type: "control", control_effect: "dmg_taken_multiplier", value: 0.9, duration: 3 }
        ], duration: 3, type: "normal", cooldown: 3, desc: "Le sort de la chance ! Sélectionne aléatoirement l'un des effets suivants : +1 PM, +100 PDV, +100 Force, +1 portée, ou résistance +10% aux dégâts. La chance est avec vous... ou pas !", icon: "🎲", animationWidth: 80, animationHeight: 80, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: -30, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight"
    },

    // Debuffs de masse (Mass Debuffs) - CD4 – effet pendant 2 tours - portée 3 – zone circulaire d'une case – type normal
    mass_deceleration: { name: "Mass Deceleration", range: 3, fixedRange: false, effect_type: "debuff", stat: "pm", value: -2, duration: 2, type: "normal", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 4, desc: "La décélération de groupe ! Tous les ennemis deviennent lents - comme des escargots en groupe !", icon: "🐌", animationWidth: 160, animationHeight: 160, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -25, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    mass_atrophy: { name: "Mass Atrophy", range: 3, fixedRange: false, effect_type: "debuff", stat: "force", value: -100, duration: 2, type: "normal", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 4, desc: "L'atrophie de groupe ! Tous les ennemis deviennent faibles - comme s'ils avaient oublié de faire du sport !", icon: "📉", animationWidth: 160, animationHeight: 160, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -25, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    mass_fog: { name: "Mass Fog", range: 3, fixedRange: false, effect_type: "debuff", stat: "accuracy", value: -20, duration: 2, type: "normal", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 4, desc: "Le brouillard de groupe ! Tous les ennemis deviennent myopes - ils ne voient plus rien !", icon: "🌫️", animationWidth: 160, animationHeight: 160, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -25, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    mass_ink: { name: "Mass Ink", range: 3, fixedRange: false, effect_type: "debuff", stat: "range", value: -1, duration: 2, type: "normal", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 4, desc: "L'encre de groupe ! Tous les ennemis deviennent myopes - comme s'ils avaient de l'encre dans les yeux !", icon: "🖤", animationWidth: 160, animationHeight: 160, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -25, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    mass_sensitivity: { name: "Mass Sensitivity", range: 3, fixedRange: false, effect_type: "control", control_effect: "dmg_taken_multiplier", value: 1.2, duration: 2, type: "normal", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 4, desc: "La sensibilité de groupe ! Tous les ennemis deviennent fragiles - ils prennent plus de dégâts !", icon: "📉", animationWidth: 160, animationHeight: 160, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -25, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // Debuffs ciblés (Targeted Debuffs) - portée 3 – CD5 – effet pendant 3 tours – cible unique – type normal
    deceleration: { name: "Deceleration", range: 3, fixedRange: false, effect_type: "debuff", stat: "pm", value: -3, duration: 3, type: "normal", cooldown: 5, desc: "La décélération ciblée ! La cible devient super lente - comme un escargot personnalisé !", icon: "🐌", animationWidth: 64, animationHeight: 128, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    atrophy: { name: "Atrophy", range: 3, fixedRange: false, effect_type: "debuff", stat: "force", value: -200, duration: 3, type: "normal", cooldown: 5, desc: "L'atrophie ciblée ! La cible devient super faible - comme si elle avait oublié de faire du sport pendant des années !", icon: "📉", animationWidth: 64, animationHeight: 128, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    ink: { name: "Ink", range: 3, fixedRange: false, effect_type: "debuff", stat: "range", value: -4, duration: 3, type: "normal", cooldown: 5, desc: "L'encre ciblée ! La cible devient myope - comme si elle avait de l'encre dans les yeux !", icon: "🖤", animationWidth: 64, animationHeight: 128, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // Buffs/Debuffs Surpuissants (2 tours) - CD 7 - portée 3 – peux s'auto-cible pour les buff
    electric_cage: { name: "Electric Cage", range: 2, fixedRange: false, effect_type: "control", control_effect: "paralyzed", duration: 3, type: "electric", cooldown: 7, desc: "Une cage électrique paralysante ! L'électricité emprisonne - la cible ne peut plus bouger !", icon: "⚡", animationWidth: 96, animationHeight: 96, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    psychosis: { name: "Psychosis", range: 2, fixedRange: false, effect_type: "control", control_effect: "confused", duration: 3, type: "psychic", cooldown: 7, desc: "La psychose qui rend fou ! Vous rendez l'ennemi fou - il ne sait plus ce qu'il fait !", icon: "🌀", animationWidth: 96, animationHeight: 96, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -30, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    funeral_song: { name: "Funeral Song", range: 2, fixedRange: false, effect_type: "control", control_effect: "sleep", duration: 3, type: "dark", cooldown: 7, desc: "La chanson funèbre qui endort ! Une mélodie si triste qu'elle endort - même les ennemis s'endorment !", icon: "🎵", animationWidth: 96, animationHeight: 192, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    flash: { name: "Flash", range: 2, fixedRange: false, effect_type: "control", control_effect: "sleep", duration: 3, type: "light", cooldown: 7, desc: "L'éclat lumineux qui éblouit ! Un flash si intense qu'il endort - comme un flash de caméra, mais en pire !", icon: "💡", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    bolt_shoes: { name: "Bolt Shoes", range: 2, fixedRange: false, effect_type: "buff", stat: "pm", value: 10, duration: 2, type: "ground", cooldown: 7, desc: "Les chaussures électriques ultimes ! Des chaussures si rapides qu'elles vous donnent des PM - comme des chaussures de course magiques !", icon: "⚡", animationWidth: 64, animationHeight: 96, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -40, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    flaming_overpower: { name: "Flaming Overpower", range: 2, fixedRange: false, effect_type: "buff", stat: "force", value: 500, duration: 2, type: "fire", cooldown: 7, desc: "La surpuissance enflammée ! Vous devenez surpuissant - comme Hulk, mais en version feu !", icon: "🔥", animationWidth: 128, animationHeight: 128, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    ancestral_root: { name: "Ancestral Root", range: 2, fixedRange: false, effect_type: "buff", stat: "maxHp", value: 500, duration: 3, type: "grass", cooldown: 7, desc: "La racine ancestrale qui vitalise ! La puissance des anciens arbres - vous devenez ultra-résistant !", icon: "🌳", animationWidth: 128, animationHeight: 128, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -40, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    falcon_eye: { name: "Falcon Eye", range: 2, fixedRange: false, effect_type: "buff", stat: "range", value: 7, duration: 3, type: "wind", cooldown: 7, desc: "L'œil de faucon ultime ! Vous voyez comme un faucon - la portée devient énorme !", icon: "🦅", animationWidth: 96, animationHeight: 96, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -40, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    titanium_shield: { name: "Titanium Shield", range: 2, fixedRange: false, effect_type: "control", control_effect: "dmg_taken_multiplier", value: 0.5, duration: 3, type: "steel", cooldown: 7, desc: "Le bouclier de titane ultime ! Un bouclier si résistant qu'il divise les dégâts par deux - comme une armure de titane !", icon: "🛡️", animationWidth: 96, animationHeight: 128, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    ultra_instinct: { name: "Ultra Instinct", range: 2, fixedRange: false, effect_type: "buff", stat: "evasion", value: 50, duration: 3, type: "water", cooldown: 7, desc: "L'instinct ultime qui esquive tout ! Vous devenez insaisissable - comme Goku en mode Ultra Instinct !", icon: "💧", animationWidth: 96, animationHeight: 96, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: -30, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    dragon_concentration: { name: "Dragon Concentration", range: 2, fixedRange: false, effect_type: "buff", stat: "crit_chance", value: 1.0, duration: 2, type: "dragon", cooldown: 7, desc: "La concentration draconique ultime ! Vous devenez parfaitement précis - TOUS vos coups sont critiques !", icon: "🐉", animationWidth: 64, animationHeight: 192, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // --- 4. TRANSMUTATION (11) - CD6 - portée 3 – cible unique – type normal – effet pendant 3 tours ---
    fire_transmutation: { name: "Fire Transmutation", range: 3, fixedRange: false, effect_type: "type_change", type_value: "fire", type: "normal", duration: 3, cooldown: 6, desc: "La transmutation en feu ! La cible devient de type Feu - attention aux brûlures !", icon: "🔥", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    water_transmutation: { name: "Water Transmutation", range: 3, fixedRange: false, effect_type: "type_change", type_value: "water", type: "normal", duration: 3, cooldown: 6, desc: "La transmutation en eau ! La cible devient de type Eau - elle devient liquide !", icon: "💧", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    electric_transmutation: { name: "Electric Transmutation", range: 3, fixedRange: false, effect_type: "type_change", type_value: "electric", type: "normal", duration: 3, cooldown: 6, desc: "La transmutation électrique ! La cible devient de type Électrique - elle devient électrique !", icon: "⚡", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    grass_transmutation: { name: "Grass Transmutation", range: 3, fixedRange: false, effect_type: "type_change", type_value: "grass", type: "normal", duration: 3, cooldown: 6, desc: "La transmutation végétale ! La cible devient végétale !", icon: "🌿", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: false, animationOnCaster: true, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    ground_transmutation: { name: "Ground Transmutation", range: 3, fixedRange: false, effect_type: "type_change", type_value: "ground", type: "normal", duration: 3, cooldown: 6, desc: "La transmutation terrestre ! La cible devient de type Sol - elle devient terreuse !", icon: "🪨", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    psy_transmutation: { name: "Psy Transmutation", range: 3, fixedRange: false, effect_type: "type_change", type_value: "psychic", type: "normal", duration: 3, cooldown: 6, desc: "La transmutation psychique ! La cible devient de type Psy - elle devient mentale !", icon: "🧠", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    wind_transmutation: { name: "Wind Transmutation", range: 3, fixedRange: false, effect_type: "type_change", type_value: "wind", type: "normal", duration: 3, cooldown: 6, desc: "La transmutation aérienne ! La cible devient de type Vent - elle devient aérienne !", icon: "💨", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    steel_transmutation: { name: "Steel Transmutation", range: 3, fixedRange: false, effect_type: "type_change", type_value: "steel", type: "normal", duration: 3, cooldown: 6, desc: "La transmutation métallique ! La cible devient de type Acier - elle devient métallique !", icon: "🛡️", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    dragon_transmutation: { name: "Dragon Transmutation", range: 3, fixedRange: false, effect_type: "type_change", type_value: "dragon", type: "normal", duration: 3, cooldown: 6, desc: "La transmutation draconique ! La cible devient de type Dragon - elle devient draconique !", icon: "🐉", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    dark_transmutation: { name: "Dark Transmutation", range: 3, fixedRange: false, effect_type: "type_change", type_value: "dark", type: "normal", duration: 3, cooldown: 6, desc: "La transmutation ténébreuse ! La cible devient de type Ténèbres - elle devient sombre !", icon: "🌑", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    light_transmutation: { name: "Light Transmutation", range: 3, fixedRange: false, effect_type: "type_change", type_value: "light", type: "normal", duration: 3, cooldown: 6, desc: "La transmutation lumineuse ! La cible devient de type Lumière - elle devient brillante !", icon: "✨", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // --- 5. DÉPLACEMENT (9) - type normal ---
    jump: { name: "Jump", range: 4, fixedRange: false, effect_type: "movement", move_direction: "teleport_self", move_distance: 4, type: "normal", cooldown: 3, no_line_of_sight: true, desc: "Un petit bond magique ! Téléportez-vous sur une case, pas besoin de ligne de vue. Parfait pour éviter les obstacles - vous sautez par-dessus tout !", icon: "💨", animationWidth: 96, animationHeight: 120, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    teleportation: { name: "Teleportation", range: 8, fixedRange: false, effect_type: "movement", move_direction: "teleport_self", move_distance: 7, type: "normal", cooldown: 5, no_line_of_sight: true, desc: "La téléportation longue distance ! Téléportez-vous sur une case, pas besoin de ligne de vue. La téléportation ultime - vous disparaissez et réapparaissez ailleurs !", icon: "🌠", animationWidth: 96, animationHeight: 120, animationDuration: 400, animationOnTarget: false, animationOnCaster: true, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    grappling_hook: { name: "Grappling Hook", range: 5, fixedRange: false, move_distance: 4, move_direction: "toward", type: "normal", cooldown: 4, desc: "Le grappin qui attire ! Comme Batman avec son grappin - vous attirez l'ennemi vers vous !", icon: "🔗", animationWidth: 48, animationHeight: 48, animationDuration: 500, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 5, particleLifetime: 12000, particleColor: "#2F353B", particleRate: 500, trajectory: "small_sine" },
    attraction: { name: "Attraction", range: 0, fixedRange: true, effect_type: "movement", move_distance: 2, move_direction: "toward", type: "normal", area: true, aoe_type: "cross", aoe_size: 3, cooldown: 4, desc: "L'attraction en croix ! Attirez toutes les cibles en croix autour de vous vers vous. Vous attirez tout autour de vous - comme un aimant magique !", icon: "👇", animationWidth: 96, animationHeight: 96, animationDuration: 700, animationOnTarget: false, animationOnCaster: true, animationYOffset: -50, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    repulsion: { name: "Repulsion", range: 1, fixedRange: true, effect_type: "movement", move_distance: 6, move_direction: "away", type: "normal", cooldown: 4, desc: "La répulsion longue portée ! l'ennemi va voler loin, très loin !", icon: "💨", animationWidth: 64, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    deliverance: { name: "Deliverance", range: 0, fixedRange: true, effect_type: "movement", move_distance: 3, move_direction: "away", type: "normal", area: true, aoe_type: "cross", aoe_size: 1, cooldown: 3, desc: "La délivrance en croix ! Vous libérez l'espace autour de vous - tout le monde s'envole !", icon: "✨", animationWidth: 128, animationHeight: 128, animationDuration: 400, animationOnTarget: false, animationOnCaster: true, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    sweep: { name: "Sweep", range: 1, fixedRange: true, effect_type: "movement", move_distance: 3, move_direction: "away", type: "normal", area: true, aoe_type: "cone", aoe_size: 4, cooldown: 5, desc: "Le balayage en cône ! Repoussez tous les ennemis en cône. Un balayage magique - tous les ennemis s'envolent en cône !", icon: "🌪️", animationWidth: 256, animationHeight: 256, animationDuration: 600, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    swap: { name: "Swap", range: 9, fixedRange: false, effect_type: "movement", move_direction: "swap", type: "normal", cooldown: 5, no_line_of_sight: true, desc: "La permutation de place ! Échangez votre position avec une cible unique, pas besoin de ligne de vue. Vous changez de place avec l'ennemi - surprise !", icon: "↔️", animationWidth: 80, animationHeight: 80, animationDuration: 700, animationOnTarget: false, animationOnCaster: true, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // --- 6. SPÉCIAUX (8) - type normal – auto-ciblage possible ---
    camouflage: { name: "Camouflage", range: 1, fixedRange: true, effect_type: "control", control_effect: "invisible", duration: 3, type: "normal", cooldown: 6, desc: "Le camouflage qui rend invisible ! Vous disparaissez complètement - même les ennemis ne vous voient plus !", icon: "🌫️", animationWidth: 96, animationHeight: 192, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: -20, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    invulnerability: { name: "Invulnerability", range: 2, fixedRange: false, effect_type: "control", control_effect: "invulnerable", duration: 2, type: "normal", cooldown: 8, desc: "L'invulnérabilité ultime !La cible devient invincible - même les dieux ne peuvent plus la toucher !", icon: "✨", animationWidth: 64, animationHeight: 64, animationDuration: 800, animationOnTarget: true, animationOnCaster: false, animationYOffset: -80, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    stasis: { name: "Stasis", range: 2, fixedRange: false, effect_type: "control", control_effect: "skip_turn", duration: 1, type: "normal", cooldown: 8, desc: "La stase qui fige ! La cible est figée dans le temps - elle ne peut plus agir !", icon: "🧊", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    mirror: { name: "Mirror", range: 2, fixedRange: false, effect_type: "control", control_effect: "reflect_damage", value: 0.5, duration: 3, type: "normal", cooldown: 8, desc: "Le miroir qui réfléchit ! La cible devient un miroir - les attaques rebondissent sur elle !", icon: "🪞", animationWidth: 96, animationHeight: 128, animationDuration: 700, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    loyalty: { name: "Loyalty", range: 3, fixedRange: false, effect_type: "control", control_effect: "damage_transfer", value: 0.5, duration: 3, type: "normal", cooldown: 6, desc: "La loyauté qui partage ! Vous partagez 50% des dommages - la loyauté a un prix !", icon: "🔗", animationWidth: 160, animationHeight: 64, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: -50, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    submission: { name: "Submission", range: 3, fixedRange: false, effect_type: "control", control_effect: "damage_transfer", value: 1.0, duration: 3, type: "normal", cooldown: 6, desc: "La soumission totale ! Vous absorbez TOUS les dégâts de la cible - la soumission ultime !", icon: "🔗", animationWidth: 120, animationHeight: 96, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    sacrifice: { name: "Sacrifice", range: 4, fixedRange: false, effect_type: "transfer", transfer_percent: 0.5, type: "normal", cooldown: 5, desc: "Le sacrifice qui soigne ! Transférez une partie de vos propres PDV actuels à une cible. Vous sacrifiez votre vie pour soigner un allié - c'est noble, mais ça fait mal !", icon: "❤️", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: -50, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    dispel: { name: "Dispel", range: 2, fixedRange: false, effect_type: "dispel", type: "normal", cooldown: 4, desc: "Le désenvoûtement qui nettoie ! Enlève tous les buffs et debuffs d'une cible. Vous nettoyez tous les effets - la cible redevient normale, comme une feuille blanche !", icon: "✨", animationWidth: 80, animationHeight: 128, animationDuration: 700, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // --- 7. SOIN (7) - Type normal – auto-ciblage possible ---
    primary_heal: { name: "Primary Heal", range: 3, fixedRange: false, effect_type: "heal", value: 20, type: "normal", cooldown: 0, desc: "Le soin de base qui fait du bien ! Le soin classique des débutants - simple, efficace, et toujours utile !", icon: "🩹", animationWidth: 64, animationHeight: 64, animationDuration: 700, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "parabolic" },
    sniper_heal: { name: "Sniper Heal", range: 7, fixedRange: false, effect_type: "heal", value: 26, type: "normal", cooldown: 2, desc: "Le soin sniper longue portée ! Vous soignez de très loin - comme un sniper, mais en version médicale !", icon: "🎯", animationWidth: 96, animationHeight: 64, animationDuration: 600, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    mass_heal: { name: "Mass Heal", range: 3, fixedRange: false, effect_type: "heal", value: 22, type: "normal", area: true, aoe_type: "circular", aoe_size: 2, cooldown: 3, desc: "Le soin de groupe ! Soigne tous les alliés en zone. Vous soignez toute l'équipe d'un coup - comme un médecin de groupe !", icon: "🌟", animationWidth: 192, animationHeight: 192, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    revitalization: { name: "Revitalization", range: 3, fixedRange: false, effect_type: "heal_over_time", value: 0.10, duration: 3, type: "normal", area: true, aoe_type: "circular", aoe_size: 1, cooldown: 5, desc: "La revitalisation progressive ! Soigne progressivement tous les alliés en zone pendant quelques tours. La régénération de groupe - vous vous soignez progressivement !", icon: "🌿", animationWidth: 128, animationHeight: 128, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    intense_heal: { name: "Intense Heal", range: 3, fixedRange: false, effect_type: "heal", value: 36, type: "normal", cooldown: 5, desc: "Le soin intense qui régénère ! Un soin puissant qui fait vraiment du bien - la cible va se sentir revivre !", icon: "💖", animationWidth: 96, animationHeight: 96, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    reconstitution: { name: "Reconstitution", range: 2, fixedRange: false, effect_type: "heal_percent", value: 1.0, type: "normal", cooldown: 9, desc: "La reconstitution ultime ! Restaure tous les PDV max de la cible. Le soin surpuissant - la cible revient à la vie complètement ! C'est presque de la résurrection !", icon: "💖", animationWidth: 96, animationHeight: 96, animationDuration: 600, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },

    // --- Actions Spéciales (Capture, Appel, Rappel) ---
    capture: { name: "Capture", range: 3, fixedRange: false, type: "normal", desc: "La capture avec une pierre ! Capturez un monstre sauvage avec une pierre de capture, portée modifiable jusqu'à 3 cases. Le sort préféré des dresseurs - attrapez-les tous !", icon: "🎯", animationWidth: 36, animationHeight: 36, animationDuration: 900, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 2, particleLifetime: 15000, particleColor: "#FFFFFF", particleRate: 200, trajectory: "parabolic", particleInterval: 0.008, maxParticles: 200, trailAlpha: 0.8 },
    summon: { name: "Appel", range: 5, fixedRange: false, type: "normal", desc: "L'appel qui invoque ! Invoquez un dofemon de votre collection sur le terrain. Faites entrer un allié en combat - l'équipe s'agrandit !", icon: "➕", animationWidth: 36, animationHeight: 36, animationDuration: 900, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 2, particleLifetime: 15000, particleColor: "#FF0000", particleRate: 200, trajectory: "parabolic", particleInterval: 0.008, maxParticles: 200, trailAlpha: 0.8, isRedTrail: true },
    recall: { name: "Rappel", range: 5, fixedRange: false, type: "normal", desc: "Le rappel qui échange ! Rappelez un dofemon actif et invoquez-en un autre de votre collection, portée modifiable jusqu'à 5 cases. Changez votre équipe en plein combat - la stratégie ultime !", icon: "🔄", animationWidth: 36, animationHeight: 36, animationDuration: 900, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 2, particleLifetime: 15000, particleColor: "#FF0000", particleRate: 200, trajectory: "parabolic", particleInterval: 0.008, maxParticles: 200, trailAlpha: 0.8, isRedTrail: true },

    // --- SORT DE TEST (À SUPPRIMER PLUS TARD) ---
    bombe_atomique: { name: "BOMBE ATOMIQUE", range: 0, fixedRange: false, damage: 1000, damageMin: 900, damageMax: 1100, type: "normal", area: true, aoe_type: "global", cooldown: 0, desc: "LA BOMBE ATOMIQUE DE TEST ! Enlève beaucoup de PDV à TOUTES les créatures adverses sur le terrain. Sort de test ultime - attention, c'est destructeur ! (À supprimer plus tard)", icon: "💣", animationWidth: 64, animationHeight: 64, animationDuration: 400, animationOnTarget: false, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
    doigt_divin: {
        name: "Le Doigt Divin", range: 5, fixedRange: false, type: "normal", cooldown: 0, effect_type: "multi_buff", multi_buffs: [
            { type: "buff", stat: "pm", value: 3, duration: 3 },
            { type: "buff", stat: "maxHp", value: 500, duration: 3 },
            { type: "buff", stat: "force", value: 500, duration: 3 },
            { type: "buff", stat: "range", value: 3, duration: 3 },
            { type: "control", control_effect: "dmg_taken_multiplier", value: 0.75, duration: 3 },
            { type: "buff", stat: "evasion", value: 50, duration: 3 }
        ], desc: "Le pouvoir divin concentré dans un doigt ! Ajoute 3 PM, 500 PDV, 500 Force, +3 portée, 25% résistance aux dégâts et 50% d'esquive. Le sort ultime qui transforme son utilisateur en être divin !", icon: "👆", animationWidth: 64, animationHeight: 64, animationDuration: 400, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight"
    },

    // --- SORT TEMPORAIRE ---
    un_pdv: { name: "1 PDV", range: 8, fixedRange: false, type: "normal", cooldown: 0, effect_type: "set_hp_to_one", desc: "Laisse un seul PDV à la cible. Un sort qui réduit les PDV de l'ennemi à 1, parfait pour affaiblir sans tuer !", icon: "💔", animationWidth: 64, animationHeight: 64, animationDuration: 500, animationOnTarget: true, animationOnCaster: false, animationYOffset: 0, particleSize: 1, particleLifetime: 0, particleColor: "#FFFFFF", particleRate: 0, trajectory: "straight" },
};

Object.values(SPELLS).forEach(spell => {
    if (spell.damage !== undefined) {
        spell.damage = Math.round(spell.damage * MultiplicateurDeDommage);
    }
    if (spell.damageMin !== undefined) {
        spell.damageMin = Math.round(spell.damageMin * MultiplicateurDeDommage);
    }
    if (spell.damageMax !== undefined) {
        spell.damageMax = Math.round(spell.damageMax * MultiplicateurDeDommage);
    }
});
